# Generated by Django 2.2.6 on 2019-10-23 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=99, unique=True, verbose_name='单词及语句')),
                ('ch_meaning', models.TextField(verbose_name='词语汉意')),
                ('word_tag', models.CharField(default='', max_length=50, verbose_name='标签')),
                ('word_image', models.ImageField(default='image/default.png', upload_to='image/user/%Y/%m', verbose_name='单词配图')),
                ('istype', models.CharField(choices=[('0', '语句'), ('1', '单词')], default='1', max_length=10, verbose_name='类型选择')),
                ('word_create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('word_update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('word_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='数据录入者')),
            ],
            options={
                'verbose_name': '单词表',
                'verbose_name_plural': '单词表',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='分类名称')),
                ('detail', models.CharField(default='', max_length=100, verbose_name='分类介绍')),
                ('icon', models.CharField(default='', max_length=100, verbose_name='分类图标')),
                ('sort_id', models.IntegerField(default=1, verbose_name='分类排序')),
                ('words', models.ManyToManyField(to='app.Word')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
    ]
