# Generated by Django 2.2.6 on 2019-10-31 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer_record',
            old_name='questionbank',
            new_name='er',
        ),
        migrations.AlterField(
            model_name='word',
            name='categorys',
            field=models.ManyToManyField(to='app.Category', verbose_name='单词分类'),
        ),
    ]
