# Generated by Django 2.2.6 on 2019-10-31 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191031_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer_record',
            name='answer',
            field=models.CharField(max_length=99, verbose_name='用户答案'),
        ),
    ]
