# Generated by Django 2.2.6 on 2019-11-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191031_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='isopen',
            field=models.CharField(choices=[('0', '私有'), ('1', '公开')], default='1', max_length=2, verbose_name='题库是否公开'),
        ),
    ]
