# Generated by Django 2.2.6 on 2019-10-24 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191023_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='words',
        ),
        migrations.AddField(
            model_name='word',
            name='categorys',
            field=models.ManyToManyField(to='app.Category'),
        ),
    ]
