# Generated by Django 2.2.6 on 2019-11-04 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_questionbank_isopen'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='c_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='分类创建者'),
        ),
    ]
