# Generated by Django 2.2.7 on 2019-11-05 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_category_c_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionbank',
            name='byuser',
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='q_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='q_user', to=settings.AUTH_USER_MODEL, verbose_name='题库创建即拥有者'),
        ),
    ]
